[WIP] Multiple levels
vanbinhstudios/thelegendofericc pull request #46
Opened 2019-03-22 23:49 UTC by fiffeek

Leave it here for the time being, just wanted to see the entire thing merged.

2019-03-24 02:14 UTC, michoecho submitted a review, later dismissed

2019-03-24 02:14 UTC, michoecho commented on core/src/com/ericc/the/game/KeyboardController.java
> +                if (DEBUG) {
Disable FieldOfViewSystem here to make this setting useful.

2019-03-24 02:14 UTC, michoecho commented on core/src/com/ericc/the/game/Engines.java
> +        if (system instanceof FieldOfViewSystem) {
Engine.getSystem() exists for when selective system update is needed. `instanceof` is a wrong tool here. Not to mention that `Engines` should not depend on `FogOfWarSystem`.

2019-03-24 02:14 UTC, michoecho commented on core/src/com/ericc/the/game/MainGame.java
> +        dungeon.generateLevel(CurrentMap.map);
All levels except the first are generated and switched inside `Dungeon`, yet the first one is generated and set by `MainGame`? This should be moved to `Dungeon`.

2019-03-24 02:14 UTC, michoecho commented on core/src/com/ericc/the/game/helpers/Moves.java
> +    public static List<List<GridPoint2>> corners =
This helper is specifically tailored for a single algorithm in `FieldOfViewSystem` and as such it should probably remain there. Also, its name is hardly fitting.

2019-03-24 02:14 UTC, michoecho commented on core/src/com/ericc/the/game/map/CurrentMap.java
> +public class CurrentMap {
Weaving the concept of __the__ current map into the architecture via static globals doesn't seem to have clear benefits. It is a potential source of problems, though, as it excludes the possibility of running multiple maps concurrently. Consider the implications of this choice for a potential multiplayer mode.

It could be wiser to tie the idea of a *current map* to players. That is, the current map is always the one hosting a player, so why not put the *current map* information into the player? The possibility of multiplayer is elegantly kept open this way.

2019-03-24 02:14 UTC, michoecho commented on core/src/com/ericc/the/game/map/Dungeon.java
> +import com.sun.istack.internal.NotNull;
Junk import.

2019-03-24 02:14 UTC, michoecho commented on core/src/com/ericc/the/game/systems/logic/TeleportPlayerSystem.java
> +public class TeleportPlayerSystem extends EntitySystem {
Whether this should be a separate system is dubitable. A teleport request is not an exceptional interaction, it is?

2019-03-24 02:14 UTC, michoecho commented on core/src/com/ericc/the/game/systems/logic/FogOfWarSystem.java
> +                if (CurrentMap.map.inBoundaries(x, y) && playersFov.visibility.get(x, y)) {
`inBoundaries()` has become redundant here.

2019-03-24 12:17 UTC, agluszak requested changes

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/Engines.java
> +        if (system instanceof FieldOfViewSystem) {
yup, to co się tu dzieje to bardzo podejrzanie wygląda

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/Engines.java
> +        this.fov.update(0);
nie rozumiem czemu to jest, dlaczego one się nie mogą normalnie updatować?

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/KeyboardController.java
> +                player.intention.currentIntent = Actions.NOTHING;
oj widzę że ktoś tu się nie zrebasował chyba :o bo ta zmiana to już jest stara przecież

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/MainGame.java
> +        dungeon.generateLevel(CurrentMap.map);
+1

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/components/DescendingComponent.java
> +public class DescendingComponent implements Component {
to jest bardzo zła nazwa, poza tym dlaczego DescendingComponent może mieć ustawione descending na false? :o

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/helpers/Moves.java
> +    public static List<List<GridPoint2>> corners =
+1

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/map/CurrentMap.java
> +public class CurrentMap {
Ja bym nie myślał za dużo o tym multiplayerze. Poza tym różnica między statyczną globalną zmienną CurrentMap a wyciąganiem tej informacji z de facto globalnego playera jest niewielka :p

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/map/CurrentMap.java
> +        engines.updatePlayersVision();
na to trzeba znaleźć jakiś ładniejszy sposób, bo obecne rozwiązanie to jest gotowanie sobie spaghetti :/

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/map/Dungeon.java
> +import com.sun.istack.internal.NotNull;
w intelliju da się ustawić automatyczne formatowanie i automatyczne ogarnianie importów przed commitem :p

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/map/Dungeon.java
> +import com.sun.istack.internal.NotNull;
a czy ktoś z codacy wyłączył ostrzeżenie o junk importach?

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/map/Dungeon.java
> +    private ArrayList<Map> levels;
Nie podoba mi się taka struktura. Lepiej zrobić jakąś klasę pamiętającą wszystkie dane o jakimś poziomie (czyli na ten moment klasę Map i listę entities) i trzymać listę takich obiektów.
Rozumiesz różnicę? To tak jak możesz przechowywać pizzę. I albo w każdym pudełku trzymasz jedną pizzę razem ze wszystkimi składnikami, albo osobno trzymasz ananasa z każdej pizzy, osobno szynkę i osobno ciasto.

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/map/Dungeon.java
> +        levels.add(new Generator(30, 30, 9).generateMap());
magiczne stałe

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/map/Map.java
> +    public GridPoint2 makeStairs(boolean descending) {
ten boolean nie wiadomo co oznacza. Proponowałbym customowy enum z dwoma wartościami (np. StairsDirection -- chociaż nie wiem czy Direction jest najlepszym słowem tutaj -- z wartościami ASCENDING i DESCENDING)

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/map/Map.java
> +    public void makeEntireMapVisibleOnFog() {
co to znaczy "visible on fog"?

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/map/Room.java
> +    public int getMinimalSize() {
nie jest jasne z nazwy co to zwraca. Chyba chodzi o dimension a nie size? I chyba nie minimal tylko, dunno, shorter? MinimalSize brzmi jak najmniejszy rozmiar jaki może mieć mapa (czyli np. 5x5)

2019-03-24 12:17 UTC, agluszak commented on core/src/com/ericc/the/game/systems/logic/TeleportPlayerSystem.java
> +    public void addedToEngine(Engine engine) {}
po co pusty override?

2019-03-24 12:42 UTC, agluszak requested changes

2019-03-24 12:42 UTC, agluszak commented on core/src/com/ericc/the/game/map/Dungeon.java
> +        if (currentLevel < entities.size()) {
`currentLevel < entities.size()`

co tu się...? :oo

2019-03-24 12:51 UTC, agluszak commented on core/src/com/ericc/the/game/map/Dungeon.java
> +        if (currentLevel < entities.size()) {
dobra, już zrozumiałem. Bo to nie jest entities, tylko entitiesPerLevel

2019-03-24 12:52 UTC, agluszak commented on core/src/com/ericc/the/game/map/Dungeon.java
> +        if (currentLevel < entities.size()) {
Sorki Filip, ale nazewnictwo serio ma znaczenie, bo przez 10 minut wpatrywałem się w ten kod i próbowałem zrozumieć czemu ilość ilość entities na obecnym poziomie ma się równać jego numerkowi xD

2019-03-24 20:27 UTC, agluszak requested changes

2019-03-24 20:27 UTC, agluszak commented on core/src/com/ericc/the/game/Engines.java
> +    public void disableFieldOfViewSystem() {
może to jest odrobinę ładniejsze, ale problem nadal pozostaje

2019-03-24 20:27 UTC, agluszak commented on core/src/com/ericc/the/game/map/LevelFactory.java
> +                StaircaseDestination.DESCENDING)
trochę bez sensu że ten parametr jest przekazywany dwa razy

2019-03-24 20:27 UTC, agluszak commented on core/src/com/ericc/the/game/map/Map.java
> +            throw new IllegalStateException("Can't find room for more entities, check the map size.");
dodałbym tutaj TODO, bo in the long run to nie jest zachowanie którego byśmy chcieli. Najlepiej by było zwracać jakieś Optional<GridPoint2> i niech wołający sam sobie sprawdzi czy to miejsce jest czy nie ma. Jak rzucimy w niego exceptionem to już prawie na pewno kaplica, a to jest exception który jednak CHCIELIBYŚMY obsłużyć w runtimie.

2019-03-24 20:27 UTC, agluszak commented on core/src/com/ericc/the/game/map/Map.java
> +            if (ctr > 50) {
same as above

2019-03-24 20:29 UTC, agluszak commented on core/src/com/ericc/the/game/Engines.java
> +    public void disableFieldOfViewSystem() {
to się napisało do złej linijki, chodziło mi o special case na rejestrowanie FogSystem i FovSYstem

2019-03-24 20:36 UTC, agluszak commented
solves #32

2019-03-25 09:30 UTC, agluszak approved these changes

2019-03-25 09:30 UTC, agluszak commented on core/src/com/ericc/the/game/map/LevelFactory.java
> +            entities.add(entrance);
O najs, to jest dużo bardziej eleganckie z tym registerStairs. Ewentualnie samo tworzenie obiektu entrance możesz przesunąć do środka ifa.

2019-03-25 12:38 UTC, merged