Time system
vanbinhstudios/thelegendofericc pull request #60
Opened 2019-04-03 10:19 UTC by agluszak

(merging into great_refactor in order to see only my changes, I will change target to dev after great_refactor gets merged)

2019-04-03 22:13 UTC, michoecho requested changes

2019-04-03 22:13 UTC, michoecho commented on core/src/com/ericc/the/game/systems/realtime/TileFadeSystem.java
> +public class TileFadeSystem extends EntitySystem {
`FadeSystem` działa zarówno na kafelki jak i na jednostki. Co podyktowało zmianę nazwy?

2019-04-03 22:13 UTC, michoecho commented on core/src/com/ericc/the/game/systems/logic/ActivitySystem.java
> +    public ActivitySystem(GameEngine gameEngine, int priority, Player player) {
Stoimy tutaj przed takim problemem: chcemy blokować aktywność w pewnych okolicznościach. W szczególności, chcemy blokować aktywność, jeśli jest kolej gracza na wykonanie akcji, a gracz nie wykonał akcji, lub jeśli wykonują się jakieś blokujące animacje.
Propozycja: zamiast uzależniać całą aktywność gry od Jedynego Słusznego Gracza™, niech istnieje BlockAction, która jest zwracana przez Agency gracza, jeśli nie podjął on żadnej innej akcji. Jeśli w danym obrocie silnika istnieje jakiś BlockAction, to ActivitySystem nic nie robi w tym obrocie. BlockingAction jest usuwane przez AgencySystem na początku update(). W ten sposób ActivitySystem nie musi wiedzieć, że istnieje gracz. Wie, że coś blokuje aktywność, a to jest dokładnie tyle, ile powinien wiedzieć.
Sprawę blokujących animacji można rozwiązać podobnie. Niech AnimationSystem przy iterowaniu się po animacjach sprawdza, czy któraś animacja jednostki jest blokująca. Jeśli tak, to dodaje jakiś AnimationBlockComponent, na który ActivitySystem reaguje tak jak na BlockAction. AnimationBlockComponent jest usuwany przez AnimationSystem na początku update().

Proponowana zmiana zwiększyłaby elastyczność systemu. Na przykład ułatwiłaby implementację limitu czasu na turę (ActivitySystem zmienia BlockAction na NoAction, jeśli minęło zbyt wiele czasu od ostatniej akcji jednostki) a nawet przerobienie gry na realtime (zamiast blokowania, szybkość upływu czasu logicznego jest uzależniana od czasu rzeczywistego).

Obserwacja: warto przy projektowaniu każdej funkcjonalności odpowiedzieć sobie na pytanie, co stałoby się, gdyby istniał więcej niż jeden gracz. Nie dlatego, że planujemy multiplayer, ale dlatego, że jeśli jakieś rozwiązanie nie daje się rozszerzyć, choć wcale nie ma przeciw temu przeszkód teoretycznych, to pewnie pojawiły się jakieś niepożądane zależności w kodzie.

2019-04-03 22:13 UTC, michoecho commented on core/src/com/ericc/the/game/systems/logic/ActivitySystem.java
> +        // Skip dying entities
Mylący kod - tak naprawdę wcale nie obchodzi nas tutaj umieranie, a przynajmniej chyba nie taki był zamiar. To, co tutaj się dokonuje, to usunięcie z kolejki jednostek, które nie powinny być w kolejce, bo gdzieś w międzyczasie straciły AgencyComponent. Tą właśnie utratę spójności należy tutaj obsługiwać, zamiast zakładać, że jedyną przyczyną utraty tego komponentu jest śmierć. Usunięcie z silnika (np. przy teleportacji) wcale nie uśmierca jednostki, a odbiera jej AgencyComponent (i wszystkie inne komponenty).

Druga rzecz: podejście, które tu jest, czyli pomijanie uszkodzonych jednostek, poprawnie obsługuje utratę komponentu, ale nie obsługuje jego pozyskania. W szczególności: nowo stworzone jednostki są ignorowane przez system do czasu następnego ruchu gracza, co jest raczej rzeczą niechcianą.

Propozycja: utrzymywanie spójności kolejki zrealizować przy pomocy listenerów.

2019-04-03 22:13 UTC, michoecho commented on core/src/com/ericc/the/game/systems/logic/ActivitySystem.java
> +            if (Mappers.active.has(entity)) {
`if` zawsze prawdziwy, z definicji `active`.

BTW, ten `if` powoduje, że jednostka, która jako ostatnia była aktywna w poprzedniej "turze", dostaje aktywność na początku następnej "tury". Przez to schody nie działają w parzystych turach, bo odpalają się przed graczem.

Drugi powód, dla którego teleportacja nie działała, to [bug](https://github.com/vanbinhstudios/thelegendofericc/commit/09394fdd99931e9a66a2b08b82e1b6577bc99e92#diff-cf797f913fceb70f116e9294aa69ff41R74) wprowadzony w 09394fd. Pozwoliłem sobie go naprawić (528500c) i wmergować tutaj.

2019-04-03 22:13 UTC, michoecho commented on core/src/com/ericc/the/game/systems/logic/ActivitySystem.java
> +                Mappers.agency.get(e).timeUnitsLeft += playerActionCost;
Nie rozumiem tej decyzji projektowej. Dlaczego gracz jest tak silnie wyróżniony?
Gracz różni się od AI tylko tym (czyż nie?), że jego Agency ma dowolnie wiele rzeczywistego czasu na dokonanie decyzji. 
Wydaje mi się, że pełne uzależnienie upływu czasu od akcji gracza (bo przy tym kształcie system czasu potrzebuje gracza, żeby działać) jest inwazyjne.
Propozycja: niech system czasu wykonuje swoją pracę w nieświadomości o graczu. Niech jednostki z kolejki po prostu wykonują kolejno swoje akcje, a gdy nadejdzie kolej gracza, system aktywności zostanie wstrzymany przez system wyboru akcji do czasu, aż gracz wykona swój ruch.

2019-04-03 22:56 UTC, michoecho requested changes
Komentarz na temat buga ze schodami.

2019-04-04 07:23 UTC, agluszak commented on core/src/com/ericc/the/game/systems/logic/ActivitySystem.java
> +                Mappers.agency.get(e).timeUnitsLeft += playerActionCost;
Hm, no ale still musimy gdzieś zwiększyć pulę TU

2019-04-04 07:26 UTC, agluszak commented on core/src/com/ericc/the/game/systems/realtime/TileFadeSystem.java
> +public class TileFadeSystem extends EntitySystem {
Racja, może odpowiedniejsze byłoby FovFadeSystem, natomiast ta zmiana w ogóle znalazła się tu zupełnie randomowo i raczej nie przynależy do tego pull requesta :p

2019-04-06 19:00 UTC, agluszak commented on core/src/com/ericc/the/game/systems/logic/ActivitySystem.java
> +            if (Mappers.active.has(entity)) {
Nie, schody nie działają, bo akcja schodów dzieje się raz na 100jc, a player może sobie biegać co 50jc.

2019-04-07 21:00 UTC, agluszak commented on core/src/com/ericc/the/game/systems/logic/MeleeAttackSystem.java
> +            attackPosition = pos.xy.shift(-1, 0);
to można przerobić na GridPoint.fromDirection

2019-04-08 17:16 UTC, fiffeek approved these changes

2019-04-08 17:16 UTC, fiffeek commented on core/src/com/ericc/the/game/Direction.java
>  }
najgorzej :-1:

2019-04-09 12:08 UTC, merged