Health and healthbars
vanbinhstudios/thelegendofericc pull request #73
Opened 2019-04-10 13:22 UTC by abstrackt

2019-04-10 18:32 UTC, fiffeek submitted a review, later dismissed

2019-04-10 18:32 UTC, fiffeek commented on core/src/com/ericc/the/game/components/HealthbarComponent.java
> +        this.zOrder = -10;
Dałbym to ciut wyżej chyba

2019-04-10 18:32 UTC, fiffeek commented on core/src/com/ericc/the/game/map/LevelFactory.java
> +            Mob mob = new Mob(map.getRandomPassableTile(), map);
Czemu tu coś się zadziało?

2019-04-10 18:32 UTC, fiffeek commented on core/src/com/ericc/the/game/systems/logic/DamageSystem.java
>  }
+newline

2019-04-12 11:14 UTC, agluszak requested changes

2019-04-12 11:14 UTC, agluszak commented on core/src/com/ericc/the/game/components/StatsComponent.java
> +        this.health = this.maxHealth;
Te nazwy są pogmatwane xD

2019-04-12 11:14 UTC, agluszak commented on core/src/com/ericc/the/game/components/AttackComponent.java
> +
Zmiana tylko pustej linijki

2019-04-12 11:14 UTC, agluszak commented on core/src/com/ericc/the/game/systems/logic/DamageSystem.java
> +            System.out.print("Initial HP: " + stats.health + " ");
Zostały logi niewyrzucone

2019-04-12 11:14 UTC, agluszak commented on core/src/com/ericc/the/game/systems/realtime/RenderSystem.java
> +                if(Mappers.position.get(b).getY() - Mappers.position.get(a).getY() != 0)
Można użyć takiego comparatora (jest czytelniejsze co tu się dzieje imo)
```
Comparator
                    .comparingInt((Entity e) -> Mappers.position.get(e).getY())
                    .reversed()
                    .thenComparing((Entity e) -> Mappers.renderable.get(e).zOrder)
                    .reversed()
```
Przy czym warto go zapisać sobie gdzieś jako private static

2019-04-12 11:15 UTC, agluszak commented on core/src/com/ericc/the/game/systems/realtime/RenderSystem.java
> +                if(Mappers.position.get(b).getY() - Mappers.position.get(a).getY() != 0)
i to dajesz jako argument do sort

2019-04-12 13:54 UTC, agluszak approved these changes

2019-04-12 13:55 UTC, merged